import { Artist, User, ArtistWallet } from "@/types";

export const MOCK_USERS: User[] = [
  {
    id: "user-navio-001",
    email: "navio@hiphopug.com",
    name: "Daniel Lubwama Kigozi",
    role: "ARTIST",
    isEmailVerified: true,
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80",
    createdAt: new Date("2024-01-01").toISOString(),
    updatedAt: new Date("2024-01-01").toISOString(),
  },
  {
    id: "user-gnl-002",
    email: "gnlzamba@hiphopug.com",
    name: "Ernest Nsimbi",
    role: "ARTIST",
    isEmailVerified: true,
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80",
    createdAt: new Date("2024-01-05").toISOString(),
    updatedAt: new Date("2024-01-05").toISOString(),
  },
  {
    id: "user-feffe-003",
    email: "feffe@hiphopug.com",
    name: "Frank Mukiiza",
    role: "ARTIST",
    isEmailVerified: true,
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80",
    createdAt: new Date("2024-01-10").toISOString(),
    updatedAt: new Date("2024-01-10").toISOString(),
  },
  {
    id: "user-judas-004",
    email: "judas@hiphopug.com",
    name: "Okello Judas",
    role: "ARTIST",
    isEmailVerified: true,
    avatarUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&auto=format&fit=crop&q=80",
    createdAt: new Date("2024-01-15").toISOString(),
    updatedAt: new Date("2024-01-15").toISOString(),
  },
  {
    id: "user-keko-005",
    email: "keko@hiphopug.com",
    name: "Jocelyn Tracey Keko",
    role: "ARTIST",
    isEmailVerified: true,
    avatarUrl: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400&auto=format&fit=crop&q=80",
    createdAt: new Date("2024-01-20").toISOString(),
    updatedAt: new Date("2024-01-20").toISOString(),
  },
];

export const MOCK_ARTISTS: Artist[] = [
  {
    id: "artist-navio-001",
    userId: "user-navio-001",
    stageName: "Navio",
    realName: "Daniel Lubwama Kigozi",
    dob: "1983-10-18",
    bio: "Pioneer of Ugandan Hip-Hop and East African rap icon. Klear Kut co-founder fusing Luganda idioms and high-octane hip-hop cadence with international acclaim.",
    region: "Kampala",
    subgenre: "Uga-Flow / Hip Hop",
    socials: {
      instagram: "https://instagram.com/naviomusic",
      x: "https://x.com/Naviomusic",
      tiktok: "https://tiktok.com/@naviomusic",
      youtube: "https://youtube.com/@NavioOfficial",
      facebook: "https://facebook.com/NavioUG",
    },
    phoneForBookings: "+256 772 001 002",
    bookingEmail: "bookings@naviomusic.com",
    // Authentic MP4 video preview (10s highlight clip)
    heroVideoMp4Url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
    heroVideoDurationSecs: 10.0,
    storageUsedBytes: 125000000, // ~125MB
    subscriptionTier: "PRO",
    isVerified: true,
    createdAt: new Date("2024-01-01T10:00:00Z").toISOString(),
    updatedAt: new Date("2024-01-01T10:00:00Z").toISOString(),
    tracks: [
      {
        id: "track-nav-01",
        artistId: "artist-navio-001",
        title: "Njogereza (Luga-HipHop Fusion)",
        durationSeconds: 218,
        fileUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
        previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
        filesizeBytes: 8400000,
        priceUgx: 3500,
        priceUsd: 0.99,
        playCount: 14200,
        downloadCount: 890,
        isPublished: true,
        createdAt: new Date("2024-01-02T10:00:00Z").toISOString(),
        updatedAt: new Date("2024-01-02T10:00:00Z").toISOString(),
        artistStageName: "Navio",
      },
      {
        id: "track-nav-02",
        artistId: "artist-navio-001",
        title: "Ngalo (Raise Your Hands)",
        durationSeconds: 235,
        fileUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
        previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
        filesizeBytes: 9100000,
        priceUgx: 3000,
        priceUsd: 0.99,
        playCount: 18900,
        downloadCount: 1240,
        isPublished: true,
        createdAt: new Date("2024-01-03T10:00:00Z").toISOString(),
        updatedAt: new Date("2024-01-03T10:00:00Z").toISOString(),
        artistStageName: "Navio",
      },
      {
        id: "track-nav-03",
        artistId: "artist-navio-001",
        title: "Rider (Kampala Nights)",
        durationSeconds: 204,
        fileUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
        previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
        filesizeBytes: 7800000,
        priceUgx: 3000,
        priceUsd: 0.99,
        playCount: 9500,
        downloadCount: 610,
        isPublished: true,
        createdAt: new Date("2024-01-04T10:00:00Z").toISOString(),
        updatedAt: new Date("2024-01-04T10:00:00Z").toISOString(),
        artistStageName: "Navio",
      },
    ],
    youtubeVideos: [
      {
        id: "yt-nav-01",
        artistId: "artist-navio-001",
        youtubeUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        videoTitle: "Navio - Njogereza (Official Music Video)",
        orderIndex: 1,
        createdAt: new Date("2024-01-02T10:00:00Z").toISOString(),
      },
      {
        id: "yt-nav-02",
        artistId: "artist-navio-001",
        youtubeUrl: "https://www.youtube.com/watch?v=kJQP7kiw5Fk",
        videoTitle: "Navio - 20 Years Live at Serena Kampala",
        orderIndex: 2,
        createdAt: new Date("2024-01-03T10:00:00Z").toISOString(),
      },
      {
        id: "yt-nav-03",
        artistId: "artist-navio-001",
        youtubeUrl: "https://www.youtube.com/watch?v=9bZkp7q19f0",
        videoTitle: "Navio ft. Klear Kut - All Stars Cypher",
        orderIndex: 3,
        createdAt: new Date("2024-01-04T10:00:00Z").toISOString(),
      },
    ],
    eventFlyers: [
      {
        id: "flyer-nav-01",
        artistId: "artist-navio-001",
        title: "20 Years of Navio Concert",
        eventDate: new Date("2026-11-20T18:00:00Z").toISOString(),
        venue: "Kampala Serena Hotel Gardens",
        city: "Kampala",
        flyerImageUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&auto=format&fit=crop&q=80",
        ticketLink: "https://ugtickets.com/navio20",
        createdAt: new Date("2024-01-05T10:00:00Z").toISOString(),
        updatedAt: new Date("2024-01-05T10:00:00Z").toISOString(),
      },
    ],
    freestyles: [
      {
        id: "free-nav-01",
        artistId: "artist-navio-001",
        title: "Midnight Kampala Cypher Bar 64",
        mediaType: "AUDIO",
        mediaUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
        durationSeconds: 120,
        createdAt: new Date("2024-01-06T10:00:00Z").toISOString(),
        updatedAt: new Date("2024-01-06T10:00:00Z").toISOString(),
      },
    ],
    services: [
      {
        id: "srv-nav-01",
        artistId: "artist-navio-001",
        serviceName: "Wedding Performance (VIP Set)",
        description: "Live 35-minute acoustic & hip-hop set with full band or backing track for your reception.",
        priceUgx: 4500000,
        priceUsd: 1200,
        isAvailable: true,
        createdAt: new Date("2024-01-02T10:00:00Z").toISOString(),
        updatedAt: new Date("2024-01-02T10:00:00Z").toISOString(),
      },
      {
        id: "srv-nav-02",
        artistId: "artist-navio-001",
        serviceName: "Club & Party Gig Appearance",
        description: "Energetic headline club host performance with crowd hype and photo opportunities.",
        priceUgx: 2500000,
        priceUsd: 700,
        isAvailable: true,
        createdAt: new Date("2024-01-02T10:00:00Z").toISOString(),
        updatedAt: new Date("2024-01-02T10:00:00Z").toISOString(),
      },
      {
        id: "srv-nav-03",
        artistId: "artist-navio-001",
        serviceName: "Guest Verse Collaboration",
        description: "Original 16-bar verse professionally tracked, mixed, and delivered for your song.",
        priceUgx: 2000000,
        priceUsd: 550,
        isAvailable: true,
        createdAt: new Date("2024-01-02T10:00:00Z").toISOString(),
        updatedAt: new Date("2024-01-02T10:00:00Z").toISOString(),
      },
    ],
  },
  {
    id: "artist-gnl-002",
    userId: "user-gnl-002",
    stageName: "GNL Zamba",
    realName: "Ernest Nsimbi",
    dob: "1986-07-28",
    bio: "The undisputed Godfather of Luga Flow. Founder of Baboon Forest Entertainment. Popularized rhyming in Luganda with cultural proverbs, social satire, and stadium-filling hits.",
    region: "Kampala",
    subgenre: "Luga Flow",
    socials: {
      instagram: "https://instagram.com/gnlzambaofficial",
      x: "https://x.com/therealgnlzamba",
      tiktok: "https://tiktok.com/@gnlzamba",
      youtube: "https://youtube.com/@GNLZamba",
      facebook: "https://facebook.com/GNLZamba",
    },
    phoneForBookings: "+256 782 112 233",
    bookingEmail: "baboonforest@gnlzamba.com",
    heroVideoMp4Url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
    heroVideoDurationSecs: 10.0,
    storageUsedBytes: 160000000,
    subscriptionTier: "PRO",
    isVerified: true,
    createdAt: new Date("2024-01-05T10:00:00Z").toISOString(),
    updatedAt: new Date("2024-01-05T10:00:00Z").toISOString(),
    tracks: [
      {
        id: "track-gnl-01",
        artistId: "artist-gnl-002",
        title: "Koyi Koyi (The Luga Riddles)",
        durationSeconds: 240,
        fileUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
        previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
        filesizeBytes: 9400000,
        priceUgx: 3500,
        priceUsd: 0.99,
        playCount: 28400,
        downloadCount: 2400,
        isPublished: true,
        createdAt: new Date("2024-01-06T10:00:00Z").toISOString(),
        updatedAt: new Date("2024-01-06T10:00:00Z").toISOString(),
        artistStageName: "GNL Zamba",
      },
      {
        id: "track-gnl-02",
        artistId: "artist-gnl-002",
        title: "Soda Jinjale",
        durationSeconds: 215,
        fileUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
        previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
        filesizeBytes: 8200000,
        priceUgx: 3000,
        priceUsd: 0.99,
        playCount: 31000,
        downloadCount: 2980,
        isPublished: true,
        createdAt: new Date("2024-01-07T10:00:00Z").toISOString(),
        updatedAt: new Date("2024-01-07T10:00:00Z").toISOString(),
        artistStageName: "GNL Zamba",
      },
      {
        id: "track-gnl-03",
        artistId: "artist-gnl-002",
        title: "Story Ya Luka",
        durationSeconds: 260,
        fileUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
        previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
        filesizeBytes: 10100000,
        priceUgx: 3000,
        priceUsd: 0.99,
        playCount: 19800,
        downloadCount: 1650,
        isPublished: true,
        createdAt: new Date("2024-01-08T10:00:00Z").toISOString(),
        updatedAt: new Date("2024-01-08T10:00:00Z").toISOString(),
        artistStageName: "GNL Zamba",
      },
    ],
    youtubeVideos: [
      {
        id: "yt-gnl-01",
        artistId: "artist-gnl-002",
        youtubeUrl: "https://www.youtube.com/watch?v=K4DyBUG242c",
        videoTitle: "GNL Zamba - Koyi Koyi Classic Visuals",
        orderIndex: 1,
        createdAt: new Date("2024-01-06T10:00:00Z").toISOString(),
      },
      {
        id: "yt-gnl-02",
        artistId: "artist-gnl-002",
        youtubeUrl: "https://www.youtube.com/watch?v=3JZ_D3ELwOQ",
        videoTitle: "GNL Zamba - The Spear Album Launch",
        orderIndex: 2,
        createdAt: new Date("2024-01-07T10:00:00Z").toISOString(),
      },
      {
        id: "yt-gnl-03",
        artistId: "artist-gnl-002",
        youtubeUrl: "https://www.youtube.com/watch?v=L_LUpnjgPso",
        videoTitle: "Luga Flow Renaissance Documentary",
        orderIndex: 3,
        createdAt: new Date("2024-01-08T10:00:00Z").toISOString(),
      },
    ],
    eventFlyers: [
      {
        id: "flyer-gnl-01",
        artistId: "artist-gnl-002",
        title: "Luga Flow Renaissance Festival",
        eventDate: new Date("2026-12-15T16:00:00Z").toISOString(),
        venue: "Lugogo Cricket Oval",
        city: "Kampala",
        flyerImageUrl: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=600&auto=format&fit=crop&q=80",
        ticketLink: "https://ugtickets.com/lugaflow2026",
        createdAt: new Date("2024-01-09T10:00:00Z").toISOString(),
        updatedAt: new Date("2024-01-09T10:00:00Z").toISOString(),
      },
    ],
    freestyles: [
      {
        id: "free-gnl-01",
        artistId: "artist-gnl-002",
        title: "Baboon Forest Cypher Freestyle Live",
        mediaType: "AUDIO",
        mediaUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
        durationSeconds: 155,
        createdAt: new Date("2024-01-10T10:00:00Z").toISOString(),
        updatedAt: new Date("2024-01-10T10:00:00Z").toISOString(),
      },
    ],
    services: [
      {
        id: "srv-gnl-01",
        artistId: "artist-gnl-002",
        serviceName: "Wedding / Kwanjula Headline Performance",
        description: "Unforgettable lyrical storytelling performance tailored for wedding introductions and receptions.",
        priceUgx: 5000000,
        priceUsd: 1350,
        isAvailable: true,
        createdAt: new Date("2024-01-06T10:00:00Z").toISOString(),
        updatedAt: new Date("2024-01-06T10:00:00Z").toISOString(),
      },
      {
        id: "srv-gnl-02",
        artistId: "artist-gnl-002",
        serviceName: "Corporate Event Brand Anthem / Cypher",
        description: "Custom composed brand anthem or corporate gala performance.",
        priceUgx: 4000000,
        priceUsd: 1100,
        isAvailable: true,
        createdAt: new Date("2024-01-06T10:00:00Z").toISOString(),
        updatedAt: new Date("2024-01-06T10:00:00Z").toISOString(),
      },
    ],
  },
  {
    id: "artist-feffe-003",
    userId: "user-feffe-003",
    stageName: "Feffe Bussi",
    realName: "Frank Mukiiza",
    dob: "1993-12-09",
    bio: "The 'Smallest Rapper' with the biggest flow. Crowned Uganda's fastest rapper with devastating punchlines and instant viral cypher records.",
    region: "Kampala",
    subgenre: "Luga Flow / Fast Rap",
    socials: {
      instagram: "https://instagram.com/feffebussi",
      x: "https://x.com/feffebussimusic",
      tiktok: "https://tiktok.com/@feffebussiofficial",
      youtube: "https://youtube.com/@FeffeBussi",
      facebook: "https://facebook.com/FeffeBussi",
    },
    phoneForBookings: "+256 701 445 667",
    bookingEmail: "feffebussi@gmail.com",
    heroVideoMp4Url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackSeeTheWorld.mp4",
    heroVideoDurationSecs: 10.0,
    storageUsedBytes: 98000000,
    subscriptionTier: "FREE",
    isVerified: true,
    createdAt: new Date("2024-01-10T10:00:00Z").toISOString(),
    updatedAt: new Date("2024-01-10T10:00:00Z").toISOString(),
    tracks: [
      {
        id: "track-fb-01",
        artistId: "artist-feffe-003",
        title: "Who Is Who (The Battle Anthem)",
        durationSeconds: 195,
        fileUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
        previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
        filesizeBytes: 7400000,
        priceUgx: 2500,
        priceUsd: 0.79,
        playCount: 42000,
        downloadCount: 3900,
        isPublished: true,
        createdAt: new Date("2024-01-11T10:00:00Z").toISOString(),
        updatedAt: new Date("2024-01-11T10:00:00Z").toISOString(),
        artistStageName: "Feffe Bussi",
      },
      {
        id: "track-fb-02",
        artistId: "artist-feffe-003",
        title: "Yes No (Street Heat)",
        durationSeconds: 180,
        fileUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3",
        previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3",
        filesizeBytes: 6900000,
        priceUgx: 3000,
        priceUsd: 0.99,
        playCount: 22000,
        downloadCount: 1800,
        isPublished: true,
        createdAt: new Date("2024-01-12T10:00:00Z").toISOString(),
        updatedAt: new Date("2024-01-12T10:00:00Z").toISOString(),
        artistStageName: "Feffe Bussi",
      },
      {
        id: "track-fb-03",
        artistId: "artist-feffe-003",
        title: "Iddi Amin Dada",
        durationSeconds: 210,
        fileUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3",
        previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3",
        filesizeBytes: 8100000,
        priceUgx: 3000,
        priceUsd: 0.99,
        playCount: 16500,
        downloadCount: 1200,
        isPublished: true,
        createdAt: new Date("2024-01-13T10:00:00Z").toISOString(),
        updatedAt: new Date("2024-01-13T10:00:00Z").toISOString(),
        artistStageName: "Feffe Bussi",
      },
    ],
    youtubeVideos: [
      {
        id: "yt-fb-01",
        artistId: "artist-feffe-003",
        youtubeUrl: "https://www.youtube.com/watch?v=kJQP7kiw5Fk",
        videoTitle: "Feffe Bussi - Who is Who Official Video",
        orderIndex: 1,
        createdAt: new Date("2024-01-11T10:00:00Z").toISOString(),
      },
      {
        id: "yt-fb-02",
        artistId: "artist-feffe-003",
        youtubeUrl: "https://www.youtube.com/watch?v=fJ9rUzIMcZQ",
        videoTitle: "Feffe Bussi Live at Freedom City",
        orderIndex: 2,
        createdAt: new Date("2024-01-12T10:00:00Z").toISOString(),
      },
      {
        id: "yt-fb-03",
        artistId: "artist-feffe-003",
        youtubeUrl: "https://www.youtube.com/watch?v=uelHwf8o7_U",
        videoTitle: "Fast Rap 100 Words in 15 Seconds",
        orderIndex: 3,
        createdAt: new Date("2024-01-13T10:00:00Z").toISOString(),
      },
    ],
    eventFlyers: [
      {
        id: "flyer-fb-01",
        artistId: "artist-feffe-003",
        title: "Hip Hop Invasion 2026",
        eventDate: new Date("2026-10-30T20:00:00Z").toISOString(),
        venue: "Club Guvnor Kampala",
        city: "Kampala",
        flyerImageUrl: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600&auto=format&fit=crop&q=80",
        ticketLink: "https://guvnor.ug/events",
        createdAt: new Date("2024-01-14T10:00:00Z").toISOString(),
        updatedAt: new Date("2024-01-14T10:00:00Z").toISOString(),
      },
    ],
    freestyles: [
      {
        id: "free-fb-01",
        artistId: "artist-feffe-003",
        title: "Acapella Punchline Storm 2026",
        mediaType: "AUDIO",
        mediaUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
        durationSeconds: 90,
        createdAt: new Date("2024-01-15T10:00:00Z").toISOString(),
        updatedAt: new Date("2024-01-15T10:00:00Z").toISOString(),
      },
    ],
    services: [
      {
        id: "srv-fb-01",
        artistId: "artist-feffe-003",
        serviceName: "Club & Campus Gig Blast",
        description: "High-intensity crowd banger performance designed to hype university balls and club bashes.",
        priceUgx: 2000000,
        priceUsd: 550,
        isAvailable: true,
        createdAt: new Date("2024-01-11T10:00:00Z").toISOString(),
        updatedAt: new Date("2024-01-11T10:00:00Z").toISOString(),
      },
      {
        id: "srv-fb-02",
        artistId: "artist-feffe-003",
        serviceName: "Party / Wedding Feature Guest",
        description: "Special comedy & punchline rap showcase at your private party or wedding.",
        priceUgx: 2500000,
        priceUsd: 680,
        isAvailable: true,
        createdAt: new Date("2024-01-11T10:00:00Z").toISOString(),
        updatedAt: new Date("2024-01-11T10:00:00Z").toISOString(),
      },
    ],
  },
  {
    id: "artist-judas-004",
    userId: "user-judas-004",
    stageName: "Judas Rapknowledge",
    realName: "Okello Judas",
    dob: "1991-04-12",
    bio: "The 'King of the North'. Dominating Luo flow and conscious rap from Gulu across the East African border. Pioneer of Northern Ugandan cyphers.",
    region: "Gulu",
    subgenre: "Luo Rap / Northern Flow",
    socials: {
      instagram: "https://instagram.com/judasrapknowledge",
      x: "https://x.com/judasrap",
      youtube: "https://youtube.com/@JudasRapknowledge",
      facebook: "https://facebook.com/JudasRapknowledge",
    },
    phoneForBookings: "+256 777 889 900",
    bookingEmail: "judasrap@gmail.com",
    heroVideoMp4Url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4",
    heroVideoDurationSecs: 10.0,
    storageUsedBytes: 85000000,
    subscriptionTier: "FREE",
    isVerified: true,
    createdAt: new Date("2024-01-15T10:00:00Z").toISOString(),
    updatedAt: new Date("2024-01-15T10:00:00Z").toISOString(),
    tracks: [
      {
        id: "track-jud-01",
        artistId: "artist-judas-004",
        title: "King of the North (Gulu Anthem)",
        durationSeconds: 228,
        fileUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
        previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
        filesizeBytes: 8700000,
        priceUgx: 2500,
        priceUsd: 0.79,
        playCount: 15400,
        downloadCount: 920,
        isPublished: true,
        createdAt: new Date("2024-01-16T10:00:00Z").toISOString(),
        updatedAt: new Date("2024-01-16T10:00:00Z").toISOString(),
        artistStageName: "Judas Rapknowledge",
      },
      {
        id: "track-jud-02",
        artistId: "artist-judas-004",
        title: "Acholi Pride Cypher",
        durationSeconds: 210,
        fileUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
        previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
        filesizeBytes: 8000000,
        priceUgx: 2500,
        priceUsd: 0.79,
        playCount: 11200,
        downloadCount: 710,
        isPublished: true,
        createdAt: new Date("2024-01-17T10:00:00Z").toISOString(),
        updatedAt: new Date("2024-01-17T10:00:00Z").toISOString(),
        artistStageName: "Judas Rapknowledge",
      },
      {
        id: "track-jud-03",
        artistId: "artist-judas-004",
        title: "Gulu Streets (Real Talk)",
        durationSeconds: 195,
        fileUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
        previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
        filesizeBytes: 7500000,
        priceUgx: 2000,
        priceUsd: 0.69,
        playCount: 9800,
        downloadCount: 540,
        isPublished: true,
        createdAt: new Date("2024-01-18T10:00:00Z").toISOString(),
        updatedAt: new Date("2024-01-18T10:00:00Z").toISOString(),
        artistStageName: "Judas Rapknowledge",
      },
    ],
    youtubeVideos: [
      {
        id: "yt-jud-01",
        artistId: "artist-judas-004",
        youtubeUrl: "https://www.youtube.com/watch?v=e-ORhEE9VVg",
        videoTitle: "Judas Rapknowledge - King of the North Video",
        orderIndex: 1,
        createdAt: new Date("2024-01-16T10:00:00Z").toISOString(),
      },
      {
        id: "yt-jud-02",
        artistId: "artist-judas-004",
        youtubeUrl: "https://www.youtube.com/watch?v=OPf0YbXqDm0",
        videoTitle: "Northern Uganda Hip-Hop Documentary",
        orderIndex: 2,
        createdAt: new Date("2024-01-17T10:00:00Z").toISOString(),
      },
      {
        id: "yt-jud-03",
        artistId: "artist-judas-004",
        youtubeUrl: "https://www.youtube.com/watch?v=kJQP7kiw5Fk",
        videoTitle: "Gulu Cypher Session Part 1",
        orderIndex: 3,
        createdAt: new Date("2024-01-18T10:00:00Z").toISOString(),
      },
    ],
    eventFlyers: [
      {
        id: "flyer-jud-01",
        artistId: "artist-judas-004",
        title: "Northern Hip Hop Fest Gulu",
        eventDate: new Date("2026-11-05T17:00:00Z").toISOString(),
        venue: "Pece Stadium Gulu",
        city: "Gulu",
        flyerImageUrl: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=600&auto=format&fit=crop&q=80",
        ticketLink: "https://ugtickets.com/gulu-fest",
        createdAt: new Date("2024-01-19T10:00:00Z").toISOString(),
        updatedAt: new Date("2024-01-19T10:00:00Z").toISOString(),
      },
    ],
    freestyles: [
      {
        id: "free-jud-01",
        artistId: "artist-judas-004",
        title: "Luo Flow Fire Session",
        mediaType: "AUDIO",
        mediaUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
        durationSeconds: 110,
        createdAt: new Date("2024-01-20T10:00:00Z").toISOString(),
        updatedAt: new Date("2024-01-20T10:00:00Z").toISOString(),
      },
    ],
    services: [
      {
        id: "srv-jud-01",
        artistId: "artist-judas-004",
        serviceName: "Festival / Community Event Headline",
        description: "Full stage Luo rap performance with dancers and hype backing.",
        priceUgx: 2000000,
        priceUsd: 550,
        isAvailable: true,
        createdAt: new Date("2024-01-16T10:00:00Z").toISOString(),
        updatedAt: new Date("2024-01-16T10:00:00Z").toISOString(),
      },
      {
        id: "srv-jud-02",
        artistId: "artist-judas-004",
        serviceName: "Club & Bar Appearance",
        description: "Live club appearance and energetic set.",
        priceUgx: 1200000,
        priceUsd: 320,
        isAvailable: true,
        createdAt: new Date("2024-01-16T10:00:00Z").toISOString(),
        updatedAt: new Date("2024-01-16T10:00:00Z").toISOString(),
      },
    ],
  },
  {
    id: "artist-keko-005",
    userId: "user-keko-005",
    stageName: "Keko",
    realName: "Jocelyn Tracey Keko",
    dob: "1987-06-03",
    bio: "Trailblazing Ugandan female emcee. Channel O Music Video Award winner, known for crisp English flow, razor-sharp cadences, and groundbreaking hip hop tracks.",
    region: "Kampala",
    subgenre: "Boom-Bap / English Rap",
    socials: {
      instagram: "https://instagram.com/kekotown",
      x: "https://x.com/kekotown",
      youtube: "https://youtube.com/@KekoMusic",
    },
    phoneForBookings: "+256 702 334 455",
    bookingEmail: "keko@kekotown.com",
    heroVideoMp4Url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    heroVideoDurationSecs: 10.0,
    storageUsedBytes: 110000000,
    subscriptionTier: "PRO",
    isVerified: true,
    createdAt: new Date("2024-01-20T10:00:00Z").toISOString(),
    updatedAt: new Date("2024-01-20T10:00:00Z").toISOString(),
    tracks: [
      {
        id: "track-keko-01",
        artistId: "artist-keko-005",
        title: "How We Do It (Pan-African Classic)",
        durationSeconds: 214,
        fileUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
        previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
        filesizeBytes: 8300000,
        priceUgx: 3000,
        priceUsd: 0.99,
        playCount: 38000,
        downloadCount: 3100,
        isPublished: true,
        createdAt: new Date("2024-01-21T10:00:00Z").toISOString(),
        updatedAt: new Date("2024-01-21T10:00:00Z").toISOString(),
        artistStageName: "Keko",
      },
      {
        id: "track-keko-02",
        artistId: "artist-keko-005",
        title: "Make You Dance (Club Banger)",
        durationSeconds: 225,
        fileUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
        previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
        filesizeBytes: 8600000,
        priceUgx: 3000,
        priceUsd: 0.99,
        playCount: 26000,
        downloadCount: 1950,
        isPublished: true,
        createdAt: new Date("2024-01-22T10:00:00Z").toISOString(),
        updatedAt: new Date("2024-01-22T10:00:00Z").toISOString(),
        artistStageName: "Keko",
      },
      {
        id: "track-keko-03",
        artistId: "artist-keko-005",
        title: "Fly Solo (Conscious Flow)",
        durationSeconds: 202,
        fileUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
        previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
        filesizeBytes: 7700000,
        priceUgx: 3000,
        priceUsd: 0.99,
        playCount: 17800,
        downloadCount: 1300,
        isPublished: true,
        createdAt: new Date("2024-01-23T10:00:00Z").toISOString(),
        updatedAt: new Date("2024-01-23T10:00:00Z").toISOString(),
        artistStageName: "Keko",
      },
    ],
    youtubeVideos: [
      {
        id: "yt-keko-01",
        artistId: "artist-keko-005",
        youtubeUrl: "https://www.youtube.com/watch?v=kJQP7kiw5Fk",
        videoTitle: "Keko - How We Do It Official Video",
        orderIndex: 1,
        createdAt: new Date("2024-01-21T10:00:00Z").toISOString(),
      },
      {
        id: "yt-keko-02",
        artistId: "artist-keko-005",
        youtubeUrl: "https://www.youtube.com/watch?v=3JZ_D3ELwOQ",
        videoTitle: "Keko - Make You Dance ft. Madtraxx",
        orderIndex: 2,
        createdAt: new Date("2024-01-22T10:00:00Z").toISOString(),
      },
      {
        id: "yt-keko-03",
        artistId: "artist-keko-005",
        youtubeUrl: "https://www.youtube.com/watch?v=9bZkp7q19f0",
        videoTitle: "Keko Live Acoustic Cypher",
        orderIndex: 3,
        createdAt: new Date("2024-01-23T10:00:00Z").toISOString(),
      },
    ],
    eventFlyers: [
      {
        id: "flyer-keko-01",
        artistId: "artist-keko-005",
        title: "Queens of African Hip Hop Night",
        eventDate: new Date("2026-12-05T20:00:00Z").toISOString(),
        venue: "National Theatre Kampala",
        city: "Kampala",
        flyerImageUrl: "https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=600&auto=format&fit=crop&q=80",
        ticketLink: "https://ugtickets.com/keko-queens",
        createdAt: new Date("2024-01-24T10:00:00Z").toISOString(),
        updatedAt: new Date("2024-01-24T10:00:00Z").toISOString(),
      },
    ],
    freestyles: [
      {
        id: "free-keko-01",
        artistId: "artist-keko-005",
        title: "Studio Raw Bars 2026",
        mediaType: "AUDIO",
        mediaUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3",
        durationSeconds: 105,
        createdAt: new Date("2024-01-25T10:00:00Z").toISOString(),
        updatedAt: new Date("2024-01-25T10:00:00Z").toISOString(),
      },
    ],
    services: [
      {
        id: "srv-keko-01",
        artistId: "artist-keko-005",
        serviceName: "Concert / Festival Headline",
        description: "Full stage performance featuring chart-topping anthems.",
        priceUgx: 3500000,
        priceUsd: 950,
        isAvailable: true,
        createdAt: new Date("2024-01-21T10:00:00Z").toISOString(),
        updatedAt: new Date("2024-01-21T10:00:00Z").toISOString(),
      },
      {
        id: "srv-keko-02",
        artistId: "artist-keko-005",
        serviceName: "Guest Feature Verse",
        description: "16 bars of sharp English hip hop recorded and stems delivered.",
        priceUgx: 1500000,
        priceUsd: 400,
        isAvailable: true,
        createdAt: new Date("2024-01-21T10:00:00Z").toISOString(),
        updatedAt: new Date("2024-01-21T10:00:00Z").toISOString(),
      },
    ],
  },
];

export const MOCK_WALLETS: Record<string, ArtistWallet> = {
  "artist-navio-001": {
    id: "wallet-navio-001",
    artistId: "artist-navio-001",
    currentBalanceUgx: 5856000, // 80% net earnings
    totalEarnedUgx: 7500000,
    totalWithdrawnUgx: 1644000,
    updatedAt: new Date().toISOString(),
  },
  "artist-gnl-002": {
    id: "wallet-gnl-002",
    artistId: "artist-gnl-002",
    currentBalanceUgx: 8240000,
    totalEarnedUgx: 10500000,
    totalWithdrawnUgx: 2260000,
    updatedAt: new Date().toISOString(),
  },
  "artist-feffe-003": {
    id: "wallet-feffe-003",
    artistId: "artist-feffe-003",
    currentBalanceUgx: 4120000,
    totalEarnedUgx: 5200000,
    totalWithdrawnUgx: 1080000,
    updatedAt: new Date().toISOString(),
  },
};
