import test from 'node:test';import assert from 'node:assert/strict';import {loadSource} from './load-source.mjs';
const operators={and:(...v)=>v,eq:(...v)=>v,inArray:(...v)=>v};
const schema={artists:{id:'artist-id'},artistImageAssets:{artistId:'artist-id',status:'status',userId:'user-id',id:'id'},artistYoutubeVideos:{artistId:'artist-id'}};
function fixture(current,selected){const writes=[];let queries=0;const tx={select:()=>({from:()=>({where:()=>({for:async()=>queries++===0?current:selected})})}),update:table=>({set:value=>({where:async()=>writes.push({table,value})})}),delete:()=>({where:async()=>{}}),insert:()=>({values:async()=>{}})};const api=loadSource('src/lib/artist-profile.ts',{'@/db':{schema},'drizzle-orm':operators,'./media-quota':{}});return{api,tx,writes};}
const artist={id:'artist',storageUsedBytes:100,subscriptionTier:'FREE'};
const saved={id:'portrait',artistId:'artist',userId:'owner',purpose:'portrait',status:'CLAIMED',actualBytes:100,blobUrl:'private',expiresAt:new Date(Date.now()+10000)};
test('profile save preserves omitted portrait and fields while explicitly clearing contacts',async()=>{const f=fixture([saved],[saved]);await f.api.applyArtistProfile(f.tx,'owner',artist,{bookingEmail:null});assert.equal(f.writes.at(-1).value.bookingEmail,null);assert.equal(f.writes.at(-1).value.storageUsedBytes,100);assert.equal(Object.hasOwn(f.writes.at(-1).value,'websiteUrl'),false);});
test('invalid replacement fails before changing claimed assets or storage',async()=>{for(const selected of [[],[{...saved,id:'new',status:'RETIRED'}],[{...saved,id:'new',purpose:'gallery'}],[{...saved,id:'new',status:'CLAIMED',artistId:'other'}]]){const f=fixture([saved],selected);await assert.rejects(f.api.applyArtistProfile(f.tx,'owner',artist,{portraitImageId:'new'}));assert.equal(f.writes.length,0);}});
test('verified replacement retires old photo and accounts only changed bytes',async()=>{const f=fixture([saved],[{...saved,id:'new',status:'UPLOADED',artistId:null,actualBytes:200}]);await f.api.applyArtistProfile(f.tx,'owner',artist,{portraitImageId:'new'});assert.equal(f.writes[0].value.status,'RETIRED');assert.equal(f.writes.at(-1).value.storageUsedBytes,200);});
